name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.UAT_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.UAT_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/uat.southland.com.au/current/
            php bin/magento c:c